version: 0.2
phases:
  pre_build:
    commands:
      - echo "Entered the pre-build phase"
  build:
    commands:
      - echo "Entered build phase"
  #   - mvn package
  post_build:
    commands:
      - echo "Entered the post-build phase"
      - mvn package
 #     - mv target/deploy ./
artifacts:
  files:
    - target/spring-mongodb-0.0.1-SNAPSHOT.jar
    - appsec.yml